### ISSUE TITLE
Submitting / Updating samples on a weekly basis

### ISSUE THREAD

**Issue by fpsom** [usegalaxy-eu/sars-cov-2-processing-requests#15]
Hi all,

([INAB-CERTH](https://inab.certh.gr/)) is sequencing roughly 100-200 samples on a weekly basis, as part of our collaboration with the National Health Organization of Greece and in the context of a flagship project on genomic surveillance. 

We deposit the raw sequences (fastq files, sequenced using Illumina and based on a slightly adapted ARCTIC protocol) to ENA under the [Project ID: PRJEB44141](https://www.ebi.ac.uk/ena/browser/view/PRJEB44141).

Although we are already analyzing these samples using the computational infrastructure of INAB-CERTH, I would be very keen in having these samples analyzed also through the Galaxy workflow - ideally also performing a re-analysis of older samples in order to assess the impact of changes in the pipeline to the final sequence / lineage assignments.

My question is this: the direct URLs of all ~2000 paired-end reads is already [here](https://www.ebi.ac.uk/ena/portal/api/filereport?accession=PRJEB44141&result=read_run&fields=study_accession,sample_accession,experiment_accession,run_accession,tax_id,scientific_name,center_name,fastq_ftp,submitted_ftp,sra_ftp&format=tsv&download=true). Should I make a copy of the links using the provided template file, which I will be changing every week, or is there a different process in place?

Thank you again for setting this up, and for your time and efforts here!

**Comment by bgruening** [comment]
@fpsom add those 2000 links would be a first great start. This repo here more or less gives you the possibility to trigger the entire stack (workflow runs, data export, dashboard update ...). If you are interested we could later integrate it into our automatic monitoring, as we do with CoG-UK. However, this assumes that your samples are produced in the same way, the metadata is complete and the automatic scripts can reason and aggregate the data based on ENA metadata.

**Comment by wm75** [comment]
@fpsom for optimal results: if you can do separate PRs per library prep or some other logical grouping of the 2000 samples, that'd be excellent. This way some of the variant reports make a bit more sense to look at.

**Comment by simonbray** [comment]
> @fpsom for optimal results: if you can do separate PRs per library prep or some other logical grouping of the 2000 samples, that'd be excellent. This way some of the variant reports make a bit more sense to look at.

Aside: it could also be multiple files in a single PR.

**Comment by fpsom** [comment]
Thank you both! We are actually using the exact same library prep, and (hopefully) metadata are complete based on the ENA Data Hub expectations.

So, I'll go ahead and put in a  PR with the ~2000 samples, as a first step, and we can see how it goes from there.

**Comment by wm75** [comment]
@fpsom just checked the ENA metadata of the samples. Under library_strategy it says `WGS` for some samples and `AMPLICONIC` for others. Knowing if just some or all of these samples have been amplified (and if so with which primer scheme) would be rather crucial.

**Comment by fpsom** [comment]
Hm. Thanks @wm75  for catching this - I'm 99.9% certain that this is an error on the metadata itself, as all these samples have been processed with the exact same protocol. However, I will do an internal check and update this issue accordingly.

**Comment by fpsom** [comment]
I've just checked with the web-lab team - all of the samples have been created using `AMPLICON` as the `library_strategy`. I'll be updated the ENA metadata as well to actually reflect that, but this may take some time.

**Comment by wm75** [comment]
@fpsom awesome! Thanks for checking and correcting the records. I'll add all these samples here to our regular bot runs then. This way they end up in one account on Galaxy together with other national genome surveillance efforts.

**Comment by wm75** [comment]
Closing this issue and the PR cause it will be handled separately.

**Comment by fpsom** [comment]
Thanks @wm75 ! Could you please tag me in the correct place, so that I know where I should be looking?

**Comment by wm75** [comment]
Sure. Your samples should get mentioned in the JSON file ftp://xfer13.crg.eu/gx-surveillance.json a day after they've been processed. In there you will find links to the corresponding analysis histories on usegalaxy.eu.
By that time (or with an adiitional day delay at most) key results files (BAMs, VCFs and consensus FASTAs) should appear on that same ftp server.
Expect this to be done by the end of the week, but I'll aalso keep an eye on the progress and let you know when everything's done.

**Comment by fpsom** [comment]
That's fantastic, thanks!

**Comment by wm75** [comment]
@fpsom you should be able to find 1,840 of your samples now on the FTP server. In the JSON file the corresponding analysis batches have "study_accession" == "PRJEB44141". BAMs, VCFs and FASTAs should be available for all of them I hope.
Pangolin lineage assignments for them will become available soon in `all_pangolin.tsv.gz` on the same server.

**Comment by wm75** [comment]
We had some processing issues for 177 samples, which I need to investigate and rerun.
For an additional 62 samples of the project the ENA lists more than one run accession per sample. We excluded these cases for the moment because it wasn't clear to us, which of the runs for these samples we should use, or whether it would be best to pool the runs.

**Comment by fpsom** [comment]
@wm75 thank you very much for the notice! I've just checked the JSON file and indeed I can see the different batches as you indicated.

I've also tried viewing the histories/reports so that I can access the files, but (as far as I can tell), an empty page loads instead. For example, I'm using the following link (`"history_link": "https://usegalaxy.eu/histories/view?id=c9e92e502f51ebaf"`) from a batch with only 6 samples (copied below for convenience).

I'm sure that I'm doing something wrong from my side, so any suggestion would be very much appreciated.

```
  "fb7b89c3694df167": {
    "batch_id": "CERTH-25-05-2021-08:34:12",
    "variation": "https://usegalaxy.eu/histories/view?id=fb7b89c3694df167",
    "samples": [
      "ERR5960501",
      "ERR5960502",
      "ERR5960503",
      "ERR5960504",
      "ERR5960505",
      "ERR5960506"
    ],
    "time": "2021-07-31T12:32:13.341555",
    "report": {
      "history_link": "https://usegalaxy.eu/histories/view?id=c9e92e502f51ebaf",
      "datamonkey_link": "https://usegalaxy.eu/api/histories/c9e92e502f51ebaf/contents/11ac94870d0bb33a4cac297db07f88f9/display"
    },
    "consensus": "https://usegalaxy.eu/histories/view?id=339d5541ccfad9e0",
    "collection_dates": [
      "2021-02-26",
      "2021-02-26",
      "2021-02-26",
      "2021-02-26",
      "2021-02-26",
      "2021-02-26"
    ],
    "study_accession": "PRJEB44141"
  },
```

**Comment by wm75** [comment]
Oh, my fault it seems. For some reason the automatic publishing of these histories didn't work so they are not accessible except from within the .eu bot account. Let me investigate and fix that.

**Comment by wm75** [comment]
@fpsom yeah, stupid me. Had forgotten to add PRJEB44141 to the projects for which we want to make data accessible. Should work now I hope.

**Comment by fpsom** [comment]
Yes, that works perfectly now! Thank you for your help on this!

**Comment by bgruening** [comment]
@fpsom pangolin assignments are now on the FTP server as well. Enjoy and if you have any feedback we would be happy to know :)
